### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by unella** [eliyas5044/angular-laravel#2]
I get an error Unexpected token  {

`C:\xampp\htdocs\angular-laravel-master>ng serve
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\node_modules\@ngtools\webpack\src\index.js:6:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\models\webpack-build-typescript.js:3:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\commands\build.js:4:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Class.module.exports.includedCommands (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\addon\index.js:21:16)
    at C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\ember-cli\lib\models\project.js:335:61
    at Array.forEach (native)
    at Project.addonCommands (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\ember-cli\lib\models\project.js:334:15)
    at Project.eachAddonCommand (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\ember-cli\lib\models\project.js:369:30)
    at module.exports (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\ember-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\ember-cli\lib\cli\cli.js:43:26)
    at tryCatch (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\xampp\htdocs\angular-laravel-master\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:2374:5)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)`

**Comment by eliyas5044** [comment]
@unella when you got this error? did you follow all step written in `READ.me` file ?
